# 该字典all为实体属性的对应二级属性要显示的字段，键值对形式，其他行业可配置
all = {
    # 实体相关
    "human": {
        # 项目需要，因此添加的字段
        'id': 'id',
        'img': 'img',
        'name': 'name',

        # 项目中删除的字段
        'Entity_id': 'Entity_id',
        'description': 'description',

        'Entity_name': 'Entity_name',
        'Chinese_name': 'Chinese_name',
        'Entity_type': 'Entity_type',
        'birth name': 'birth name',
        'name in native language': 'name in native language',
        'nickname': 'nickname',
        'date of birth': 'date of birth',
        'date of death': 'date of death',
        'date of disappearance': 'date of disappearance',
        'place of birth': 'place of birth',
        'country of citizenship': 'country of citizenship',
        'ethic group': 'ethic group',
        'religion': 'religion',
        'occupation': 'occupation',
        'military rank': 'military rank',
        'military branch': 'military branch',
        'member of political party': 'member of political party',
        'award received': 'award received',
        'e-mail': 'e-mail',
        'official blog': 'official blog',
        'official website': 'official website',
        'summary': 'summary',
        'English_text': 'English_text',
        'Chinese_text': 'Chinese_text'
    },
    "organization": {
        'id': 'id',
        'img': 'img',
        'Entity_name': 'Entity_name',
        'Chinese_name': 'Chinese_name',
        'Entity_type': 'Entity_type',
        'description': 'description',
        'native label': 'native label',
        'short name': "short name",
        'headquarters location': 'headquarters location',
        'type': 'type',
        'inception': 'inception',
        'member count': 'member count',
        'employees': 'employees',
        'political ideology': 'political ideology',
        'official website': 'official website',
        'telephone number': 'telephone number',
        'English_text': 'English_text',
        'Chinese_text': 'Chinese_text',
        'name': 'name'
    },
    "administrative": {
        'id': 'id',
        'img': 'img',
        'Entity_name': 'Entity_name',
        'Chinese_name': 'Chinese_name',
        'Entity_type': 'Entity_type',
        'description': 'description',
        'official name': 'official name',
        'name in native language': 'name in native language',
        'replaces': 'replaces',
        'replaces by': 'replaces by',
        'nickname': 'nickname',
        'short name': 'short name',
        'inception': 'inception',
        'capital': 'capital',
        'continent': 'continent',
        'country': 'country',
        'area': 'area',
        'located in or next to body of water': 'located in or next to body of water',
        'population': 'population',
        'GDP': 'GDP',
        'gini coefficient': 'gini coefficient',
        'located in time zone': 'located in time zone',
        'coordinate location': 'coordinate location',
        'local dialing code': 'local dialing code',
        'postal code': 'postal code',
        'top-level Internet domain': 'top-level Internet domain',
        'official website': 'official website',
        'office blog': 'office blog',
        'English_text': 'English_text',
        'Chinese_text': 'Chinese_text',
        'name': 'name'
    },
    "weapon": {
        'id': 'id',
        'img': 'img',
        'Entity_name': 'Entity_name',
        'Chinese_name': 'Chinese_name',
        'Entity_type': 'Entity_type',
        'image': 'image',
        'coat of arms image': 'coat of arms image',
        'vessel class': 'vessel class',
        'location of final assembly': 'location of final assembly',
        'total produced': 'total produced',
        'inception': 'inception',
        'first flight': 'first flight',
        'service entry': 'service entry',
        'service retirement': 'service retirement',
        'use': 'use',
        'cost': 'cost',
        'muzzle velocity': 'muzzle velocity',
        'length': 'length',
        'width': 'width',
        'height': 'height',
        'mass': 'mass',
        'bore': 'bore',
        'diameter': 'diameter',
        'wingspan': 'wingspan',
        'takeoff and landing capability': 'takeoff and landing capability',
        'conflict': 'conflict',
        'significant event': 'significant event',
        'participant of': 'participant of',
        'armament': 'armament',
        'coordinate location': 'coordinate location',
        'call sign': 'call sign',
        'pennant number': 'pennant number',
        'official website': 'official website',
        'English_text': 'English_text',
        'Chinese_text': 'Chinese_text',
        'description': 'description',
        'name': 'name'
    },
    "CyberUser": {
        'id': 'id',
        'img': 'img',
        'Entity_name': 'Entity_name',
        'Chinese_name': 'Chinese_name',
        'Entity_type': 'Entity_type',
        'English_text': 'English_text',
        'Chinese_text': 'Chinese_text',
        'description': 'description',
        'name': 'name',
        "real_name": "real_name",
        "location": "location",
        "url": "url",
        "followers_count": "followers_count",
        "friends_count": "friends_count",
        "listed_count": "listed_count",
        "favourites_count": "favourites_count",
        "statuses_count": "statuses_count"
    },
    "other": {
        'id': 'id',
        'img': 'img',
        'Entity_name': 'Entity_name',
        'Chinese_name': 'Chinese_name',
        'Entity_type': 'Entity_type',
        'English_text': 'English_text',
        'Chinese_text': 'Chinese_text',
        'description': 'description',
        'name': 'name'
    },
    "geographic_entity": {

    },
    # 事件相关
    "event": {
        '_id': '_id',
        'id': 'id',
        'event_type': 'event_type',
        'event_subtype': 'event_subtype',
        'event_content': 'event_content',
        'entity_list': 'entity_list',
        'time_list': 'time_list',
        'location_list': 'location_list',
        'publish_time': 'publish_time',
        'description': 'description'
    },
    # 文档相关
    "document": {
        '_id': '_id',
        'id': 'id',
        'channel': 'channel',
        'site_name': 'site_name',
        'title': 'title',
        'content': 'content',
        'publish_time': 'publish_time',
        'time': 'time',
        'topic': 'topic',
        'entity_list': 'entity_list',
        'description': 'description'
    }
}

translate = {
    "human": {
        all['human']['id']: '实体',
        all['human']['img']: '图标',
        all['human']['Entity_name']: '名称',
        all['human']['Chinese_name']: '中文名',
        all['human']['Entity_type']: '类型',
        all['human']['birth name']: '全名',
        all['human']['name in native language']: '母语名',
        all['human']['nickname']: '昵称',
        all['human']['date of birth']: '出生日期',
        all['human']['date of death']: '死亡日期',
        all['human']['date of disappearance']: '失踪日期',
        all['human']['place of birth']: '出生地',
        all['human']['country of citizenship']: '国籍',
        all['human']['ethic group']: '所属民族',
        all['human']['religion']: '宗教信仰',
        all['human']['occupation']: '从事职业',
        all['human']['military rank']: '军衔',
        all['human']['military branch']: '所属军种',
        all['human']['member of political party']: '所属政党',
        all['human']['award received']: '荣誉',
        all['human']['e-mail']: '邮箱',
        all['human']['official blog']: '博客',
        all['human']['official website']: '官网',
        all['human']['summary']: '简介',
        all['human']['English_text']: '英文简介',
        all['human']['Chinese_text']: '中文简介',
        all['human']['description']: '描述',
        all['human']['name']: '姓名'
    },
    "organization": {
        all['organization']['id']: '实体',
        all['organization']['img']: '图标',
        all['organization']['Entity_name']: '名称',
        all['organization']['Chinese_name']: '中文名',
        all['organization']['Entity_type']: '类型',
        all['organization']['description']: '描述',
        all['organization']['native label']: '母语名',
        all['organization']['short name']: "简称",
        all['organization']['headquarters location']: '组织总部',
        all['organization']['type']: '组织类型',
        all['organization']['inception']: '成立时间',
        all['organization']['member count']: '组织成员数',
        all['organization']['employees']: '组织员工数',
        all['organization']['political ideology']: '意识形态',
        all['organization']['official website']: '官网',
        all['organization']['telephone number']: '电话',
        all['organization']['English_text']: '英文简介',
        all['organization']['Chinese_text']: '中文简称',
        all['organization']['name']: '姓名',
    },
    "administrative": {
        all['administrative']['id']: '实体',
        all['administrative']['img']: '图标',
        all['administrative']['Entity_name']: '名称',
        all['administrative']['Chinese_name']: '中文名',
        all['administrative']['Entity_type']: '类型',
        all['administrative']['description']: '描述',
        all['administrative']['official name']: '全名',
        all['administrative']['name in native language']: '母语名',
        all['administrative']['replaces']: '曾用名',
        all['administrative']['replaces by']: '现用名',
        all['administrative']['nickname']: '昵称',
        all['administrative']['short name']: '简称',
        all['administrative']['inception']: '建立时间',
        all['administrative']['capital']: '首府',
        all['administrative']['continent']: '所属大陆',
        all['administrative']['country']: '所属国家',
        all['administrative']['area']: '陆地面积',
        all['administrative']['located in or next to body of water']: '水域面积',
        all['administrative']['population']: '人口',
        all['administrative']['GDP']: 'GDP',
        all['administrative']['gini coefficient']: '基尼系数',
        all['administrative']['located in time zone']: '时区',
        all['administrative']['coordinate location']: '坐标',
        all['administrative']['local dialing code']: '电话区号',
        all['administrative']['postal code']: '邮编',
        all['administrative']['top-level Internet domain']: '顶级域名',
        all['administrative']['official website']: '官网',
        all['administrative']['office blog']: '博客',
        all['administrative']['English_text']: '英文简介',
        all['administrative']['Chinese_text']: '中文简称',
        all['administrative']['name']: '姓名',
    },
    "weapon": {
        all['weapon']['id']: '实体',
        all['weapon']['img']: '图标',
        all['weapon']['Entity_name']: '名称',
        all['weapon']['Chinese_name']: '中文名',
        all['weapon']['Entity_type']: '类型',
        all['weapon']['image']: 'image',
        all['weapon']['coat of arms image']: '相关多媒体',
        all['weapon']['vessel class']: '舰级',
        all['weapon']['location of final assembly']: '总装地点',
        all['weapon']['total produced']: '总产量',
        all['weapon']['inception']: '诞生时间',
        all['weapon']['first flight']: '首航日期',
        all['weapon']['service entry']: '入役时间',
        all['weapon']['service retirement']: '退役时间',
        all['weapon']['use']: '飞行用途',
        all['weapon']['cost']: '造价',
        all['weapon']['muzzle velocity']: '枪口初速度',
        all['weapon']['length']: '长度',
        all['weapon']['width']: '宽度',
        all['weapon']['height']: '高度',
        all['weapon']['mass']: '武器重量',
        all['weapon']['bore']: '枪支口径',
        all['weapon']['diameter']: '武器直径',
        all['weapon']['wingspan']: '翼展',
        all['weapon']['takeoff and landing capability']: '降落方式',
        all['weapon']['conflict']: '参与事件',
        all['weapon']['significant event']: '参与事件',
        all['weapon']['participant of']: '参与事件',
        all['weapon']['armament']: '装载武器',
        all['weapon']['coordinate location']: '驻扎点',
        all['weapon']['call sign']: '船舶信号',
        all['weapon']['pennant number']: '舷号',
        all['weapon']['official website']: '官方网站',
        all['weapon']['English_text']: '英文简介',
        all['weapon']['Chinese_text']: '中文简称',
        all['weapon']['description']: '描述',
        all['weapon']['name']: '姓名',
    },
    "CyberUser": {
        all['CyberUser']['id']: '实体',
        all['CyberUser']['img']: '图标',
        all['CyberUser']['Entity_name']: '名称',
        all['CyberUser']['Chinese_name']: '中文名',
        all['CyberUser']['Entity_type']: '类型',
        all['CyberUser']['English_text']: '英文简介',
        all['CyberUser']['Chinese_text']: '中文简称',
        all['CyberUser']['description']: '描述',
        all['CyberUser']['name']: '姓名',

        all['CyberUser']['real_name']: '真实姓名',
        all['CyberUser']['location']: '位置',
        all['CyberUser']['url']: '链接',
        all['CyberUser']['followers_count']: '粉丝',
        all['CyberUser']['friends_count']: '关注',
        all['CyberUser']['listed_count']: '媒体',
        all['CyberUser']['favourites_count']: '喜欢',
        all['CyberUser']['statuses_count']: '推文'
    },
    "other": {
        all['other']['id']: '实体',
        all['other']['img']: '图标',
        all['other']['Entity_name']: '名称',
        all['other']['Chinese_name']: '中文名',
        all['other']['Entity_type']: '类型',
        all['other']['English_text']: '英文简介',
        all['other']['Chinese_text']: '中文简称',
        all['other']['description']: '描述',
        all['other']['name']: '姓名'
    },
    "geographic_entity": {

    },
    "event": {
        all['event']['_id']: '_id',
        all['event']['id']: 'id',
        all['event']['event_type']: '事件类型',
        all['event']['event_subtype']: '事件子类型',
        all['event']['event_content']: '描述',
        all['event']['entity_list']: '提及实体',
        all['event']['time_list']: '提及时间',
        all['event']['location_list']: '提及地点',
        all['event']['publish_time']: '发生时间',
        all['event']['description']: '描述'
    },
    "document": {
        all['document']['_id']: '_id',
        all['document']['id']: 'id',
        all['document']['channel']: '通道',
        all['document']['site_name']: '数据来源',
        all['document']['title']: '标题',
        all['document']['content']: '描述',
        all['document']['description']: '描述',
        all['document']['publish_time']: '发布时间',
        all['document']['time']: '时间',
        all['document']['topic']: '主题分类',
        all['document']['entity_list']: '实体列表'
    }
}
