""" translate edge's English type to Chinese type"""

from collections import defaultdict

default_value = None

translate_dict = {
    # human
    "spouse": "夫妻",
    "mother": "母亲",
    "father": "父亲",
    "child": "子女",
    "sibling": "兄弟姐妹",
    "partner": "合伙人",
    "occupation": "职业",
    "member of political party": "所属政党",
    "country of citizenship": "国籍",
    "member of": "所属组织",
    "employer": "雇主",
    "educated at": "教育经历",
    "work at": "工作经历",
    "employee": "雇员",
    "position held": "职位",
    "chairperson": "主席",
    # 组织
    "business division": "业务部门",
    "parent organization": "上级部门",
    "subsidiary": "下级部门",
    "chief executive officer": "首席执行官",
    "founded by": "创办者",
    "chief operating officer": "首席运营官",
    "chairperson": "领袖",
    "has part": "包含",
    "host": "主持人",
    "employer": "雇主",
    "buyer": "买主",
    "org": "非盈利组织",
    # 国家
    "country": "国家",
    "capital": "首府",
    "twinned administrative body": "结盟行政机构",
    "contains administrative territorial entity": "下属地区",
    "located in the administrative territorial entity": "位于",
    "diplomatic relation": "邦交国家",
    "shares border with": "接壤",
    "highest judicial authority": "最高司法机关",
    "legislative body": "立法机构",
    "executive body": "执行政府",
    "office held by head of government": "政府机构",
    "head of government": "政府首长",
    "head of state": "国家元首",
    "Twitter username": "twitter账号",
    "Facebook ID": "facebook 账号",
    # 假实体ID关系拓展
    "target_identity": "目标身份",
    "type": "类型",

    # 地理特征
    "work location": "工作地点",
    "central bank": "中央银行",
    "part of": "部分",
    "owner of": "产权所有人",
    "sister city": "友好城市",
    "contains administrative territorial entity": "包含行政领土",

    # 事件
    "include_entity": "包含",
    "include_event": "包含",
    "event_city": "事件城市",
    "event_region": "事件范围",
    "target_nation": "目标位置",
    "event_country": "事件国家",
    "entity_name": "事件名称",
    # 其他，待优化
    "origin": "起源",
    "adjudicator": "判决方",
    "agent": "加害者",
    "entity": "实体",
    "victim": "受害者",
    "event_location": "事件地点",
    "destination": "目的地",
    "place": "地点",
    "giver": "给予方",
    "plaintiff": "原告方",
    "artifact": "传输主体",
    "attacker": "攻击者",
    "recipient": "接收方",
    "target": "目标",
    "person": "主体",
    "defendant": "被告方",
    "position": "职位",
    "attack": "攻击",
    "Attack": "攻击",
    "related": "共现",
    # project相关
    "chairperson": "主席",
    "belong to": "属于",
    # social_media_twitter
    "publish": "发布",
    "mention": "提及",
    "forward": "转发",

    # 拓展节点类型用于替代document关系的"包含"
    "human": "主体",
    "organization": "组织",
    "administrative": "地区",
    "weapon": "武器",
    "project": "项目",
    "geographic_entity": "地理特征",
    "event": "事件",
    "document": "文档"

}
nodes_translate_dict = {
    # document-nodes
    "polotics": "政治",
    "politic": "拉选",
    "military": "军事",
    "economy": "经济",
    "religion": "宗教",
    "culture": "文化",
    "science": "科技",
    "sport": "体育",
    "daily": "生活",
    "recreation": "娱乐",
    "business": "商业",
    "health": "健康",
    "security": "安全",
    "sports": "运动",
    # event-nodes
    "release-parole": "假释",
    "ne-born": "诞生",
    "marry": "结婚",
    "divorce": "离婚",
    "injure": "伤害",
    "die": "死亡",
    "transport": "运输",
    "transfer-ownership": "所有权交易",
    "transfer-money": "金钱交易",
    "start-org": "组织创建",
    "merge-org": "组织合并",
    "declare-bankruptcy": "宣布破产",
    "end-org": "组织结束",
    "attack": "攻击",
    "demonstrate": "游行示威",
    "meet": "会面",
    "phone-write": "电话-书信",
    "start-postition": "开始职位",
    "end-position": "结束职位",
    "nominate": "提名",
    "elect": "选举",
    "arrest-jail": "逮捕",
    "trial-hearing": "审讯",
    "charge-indict": "起诉",
    "sue": "控告",
    "convict": "定罪",
    "sentence": "判决",
    "fine": "罚款",
    "execute": "处死",
    "extradite": "引渡",
    "acquit": "无罪释放",
    "appeal": "赦免",
    "pardon": "上诉",
}

translate_dict = defaultdict(lambda: default_value, translate_dict)
nodes_translate_dict = defaultdict(lambda: default_value, nodes_translate_dict)
